### ISSUE TITLE
Split bundle doesn't work in Angular

### ISSUE THREAD

**Issue by coxp** [onfido/onfido-sdk-ui#2173]
We are trying to use the split bundle to see if this solves the issue of bad dependencies in the main bundle but this doesn't seem to work in a basic angular project. Is this because the split bundle isn't correctly supporting ESModules?

Can you add an Angular sample app for the library alongside the vanilla JS and React sample apps? It would be helpful to have a sample app showing both the normal import method and also using the split bundle.

`import { init } from 'onfido-sdk-ui/split';`

`Cannot find module 'onfido-sdk-ui/split' or its corresponding type declarations.ts (2307)`

**Comment by billpull** [comment]
Having same issue within NextJS application. "onfido-sdk-ui" resolves but "onfido-sdk-ui/split" does not.

**Comment by gurpreet-onfido** [comment]
Hello there!

Greetings for the day!

Our team has fixed this issue and we will let you know once the fix is released. 

Stay tuned!

Kind regards
Gurpreet Singh

**Comment by coxp** [comment]
Just to check, will this fix the bundle size issue when using the latest versions as the current bundle is 6x larger than the version we are currently using. 

We are currently using v6.18.0 for video reports and we want to move to a later version to enable motion reports. Is v6.18 still downloading 11Mb but just lazy loading the other libraries and v13.1.0 is including them directly in the bundle so no lazy loading happens? Essentially though, if we're using motion reports then we'll end up downloading the whole 11Mb whether we use the old library, the new split bundle, or the current library?

| Module | Size (bytes) |
| ------ | ------------ |
| webpack:///node_modules/onfido-sdk-ui/lib/index.js | 5763680 |
| webpack:///node_modules/@onfido/active-video-capture/dist/index.umd.cjs | 3343471 |
| webpack:///node_modules/@onfido/opencv/dist/opencv.js | 1799406 |

| Version | Uncompressed Size |
| ------- | ----------------- |
| v5.0.0 | doesn't build |
| v6.0.0 | doesn't build |
| v6.5.0 | doesn't build |
| v6.7.0 | 1.70 MB |
| v6.9.0 | 1.80 MB |
| v6.15.6 | 2.02 MB |
| v8.0.0 | 2.12 MB |
| v8.1.0 | 2.29 MB |
| v8.1.1 | 2.29 MB |
| v8.2.0-rc.1 | 5.21 MB |
| v8.3.0 | 5.21 MB |
| v9.0.0 | 5.32 MB |
| v9.1.5 | 5.34 MB |
| v10.0.0 | doesn't build |
| v10.4.1 | doesn't build |
| v11.0.0 | doesn't build |
| v12.0.0 | doesn't build |
| v12.1.0 | doesn't build |
| v12.2.0 | doesn't build |
| v12.3.0 | 11.01 MB |
| v12.4.1 | 11.04 MB |
| v13.0.1 | 11.04 MB |
| v13.1.0 | 11.08 MB |

**Comment by coxp** [comment]
@gurpreet-onfido Hi Gurpreet, is there any update on when this will be released?

**Comment by gurpreet-onfido** [comment]
@coxp I am so sorry that I missed to update you here. This is already resolved in 13.1.0 version of the SDK.

Kind regards
Gurpreet Singh

**Comment by coxp** [comment]
> @coxp I am so sorry that I missed to update you here. This is already resolved in 13.1.0 version of the SDK.
> 
> Kind regards Gurpreet Singh

@gurpreet-onfido Can we get an example angular project from the team for this as this still doesn't work for me with 13.3.1?

There's a simple sample project here https://github.com/coxp/of-example
