### ISSUE TITLE
Unable to run with Create React App or Storybook

### ISSUE THREAD

**Issue by afkatja** [onfido/onfido-sdk-ui#615]
I'm trying to run the Onfido app in isolation and so I created a single POC app with Create React App.

````
import React, { Component } from "react";
import PropTypes from "prop-types";
import Onfido from "onfido-sdk-ui";

class OnfidoConnector extends Component {
  constructor(props) {
    super(props);
    this.state = {
      onfidoToken: ""
    };
  }

  initializeOnfido = (token, showModal) => {
    console.log("initializing", token, Onfido);
    if (Onfido && Object.keys(Onfido).length) {
      Onfido.init({
        // the JWT token that you generated earlier on
        token,
        // id of the element you want to mount the component on
        containerId: "onfido-mount",
        documentTypes: {
          driving_licence: true
        },
        useModal: showModal,
        isModalOpen: showModal,
        onModalRequestClose: function() {
          // Update options with the state of the modal
          Onfido.setOptions({ isModalOpen: false });
        },
        steps: [
          "document",
          {
            type: "face",
            options: { requestedVariant: "video" }
          },
          "complete"
        ],
        onComplete: function(data) {
          console.log("everything is complete", data);
        }
      });
    }
  };

  componentDidMount() {
    const tempToken = "...";
    this.initializeOnfido(tempToken, false);
  }

  render() {
    return <div id="onfido-mount" />;
  }
}

export default OnfidoConnector;

````

my dependencies in `package.json`:
````
  "devDependencies": {
    "@babel/cli": "^7.1.5",
    "@babel/core": "^7.1.6",
    "@babel/plugin-proposal-class-properties": "^7.2.3",
    "@babel/plugin-proposal-object-rest-spread": "^7.2.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.4",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "@storybook/react": "^5.0.6",
    "@storybook/addon-actions": "^5.0.6",
    "@storybook/addon-links": "^5.0.6",
    "@storybook/addons": "^5.0.6"
  },
  "dependencies": {
    "@babel/polyfill": "^7.0.0",
    "react": "^16.8.6",
    "isomorphic-fetch": "^2.2.1",
    "onfido-sdk-ui": "^5.0.0",
    "react-dom": "^16.6.3"
  }
````

The sdk token is passed from the internal API and it works fine.

The app won't even start, getting `Uncaught TypeError: Cannot read property 'dispose' of undefined at Object../node_modules/react-dev-utils/webpackHotDevClient.js` and `Uncaught Error: Iframe has not been created yet.`

Trying to run the component as a story in storybook results in `TypeError: Object(...) is not a function at Module.push../node_modules/onfido-sdk-ui/lib/index.js`. If I import Onfido not the es6 way but as `const Onfido = require("onfido-sdk-ui");` results in `Onfido` being an empty object.

Either way, I'm stuck without understanding what's actually going wrong. 
1. What is the preferred way of importing Onfido in a React Component? 
2. Has anyone succeeded in running the component in Storybook?
3. Has anyone succeeded in running the component as a CRA application?

Any help will be greatly appreciated.

**Comment by stefaniacardenas** [comment]
Hi, 
the following import styles should all work
`import * as Onfido from "onfido-sdk-ui"`
or you could just import the init function
`import { init } from "onfido-sdk-ui"`
`const Onfido = require("onfido-sdk-ui")` should work but maybe it fails with Storybook/CRA due to the way Webpack 4+ exports the module.

**Comment by afkatja** [comment]
Hi Stegania,

Thanks for your reply.
> `const Onfido = require("onfido-sdk-ui")` should work but maybe it fails with Storybook/CRA due to the way Webpack 4+ exports the module.
What would you suggest in this case? I now try doing async/await requiring the module and still it fails for the storybook...

**Comment by stefaniacardenas** [comment]
I can successfully import the module using `const Onfido = require("onfido-sdk-ui")` in a demo app, so I cannot reproduce the issue to investigate it further. 
What was the outcome when using `import * as Onfido from "onfido-sdk-ui"` and `import { init } from "onfido-sdk-ui"`?

**Comment by isitrita** [comment]
@afkatja Were you able to solve the problem? I encounter looking-similar issue, got underfined accept for modules.hot.accept.

**Comment by afkatja** [comment]
@isitrita @stefaniacardenas Nope I could not solve the problem. Neither `import Onfido from 'onfido-sdk-ui'` nor `require('onfido-sdk-ui')` nor even `await require('onfido-sdk-ui')` let me use the app in storybook or React Create App.

**Comment by stefaniacardenas** [comment]
Hi! Sorry to hear you are having problem importing the library. I will open a ticket and investigate on this ASAP.
In version `4.0.0` we changed the way Webpack does the import/export transpilation and I suspect this might be the cause of the issue.
Could you try installing version `3.1.0` and see if it makes any difference?

**Comment by azriel46d** [comment]
I'm having the same issue when utilising it with react including version ```3.1.0``` Is there something maybe we are skipping in terms of webpack configuration?

**Comment by fernandez14** [comment]
I'm also having issues with this...

It worked using the 3.1.0 but I dont think is the best way to go, any ideas?

**Comment by rfreitas** [comment]
Have you guys tried taking a look at the project I mention here: https://github.com/onfido/onfido-sdk-ui/issues/624#issuecomment-489105493 It seems to be working. If we can replicate your case in this environment we might be able to figure it out.

**Comment by azriel46d** [comment]
@rfreitas couldn't figure out how to do the changes  to the react app without ejecting the webpack config. What I found out is that if instead of 
```
import * as Onfido from 'onfido-sdk-ui'
```
I did 
```
import * as Onfido from "onfido-sdk-ui/dist/onfido.min.js"
import "onfido-sdk-ui/dist/style.css"
```
In this way it works. 
if I try importing the library directly
```
import * as Onfido from "onfido-sdk-ui/lib/index.js"
```

This causes the issue as well

**Comment by yctercero** [comment]
I was encountering the same exact issue when trying to use the latest version. @azriel46d 's suggestion worked for me on an ejected react create app config.

**Comment by stefanmaric** [comment]
We are having the same issue with a custom webpack config and @azriel46d's workaround worked for us.

**Comment by stefaniacardenas** [comment]
Hi, the issue related with importing the library has been fixed in release [5.3.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.3.0).
I've tested it in a CRA project and in Storybook.
You should now be able to import `onfido-sdk-ui` using one of the following import styles:
`import * as Onfido from "onfido-sdk-ui"`
`import { init } from "onfido-sdk-ui"`
`const Onfido = require("onfido-sdk-ui")`
I will close this issue for now. Feel free to reopen if you encounter any problem.

**Comment by dhavalsoni2001** [comment]
@stefaniacardenas  I am still facing the issue and I am on version 5.3.0

 ● Test suite failed to run

    TypeError: Cannot read property 'indexOf' of null



      at Object.<anonymous> (node_modules/supports-webp/dist/supports-webp.common-js.js:6:62)
      at Object.<anonymous> (node_modules/onfido-sdk-ui/lib/index.js:12:47776)
      at n (node_modules/onfido-sdk-ui/lib/index.js:1:151)
      at Module.<anonymous> (node_modules/onfido-sdk-ui/lib/index.js:17:393988)
      at n (node_modules/onfido-sdk-ui/lib/index.js:1:151)
      at node_modules/onfido-sdk-ui/lib/index.js:1:1006
      at Object.<anonymous> (node_modules/onfido-sdk-ui/lib/index.js:1:1017)
      at Object.<anonymous> (app/containers/MyOffer/Overview/index.js:934:16)
      at Object.<anonymous> (app/containers/index.js:553:36)
      at Object.<anonymous> (app/containers/App/index.js:898:38)
      at Object.<anonymous> (app/app.js:22:35)
      at Object.<anonymous> (app/utils/commonFunctions.js:1966:8)
      at Object.<anonymous> (app/containers/MyApplication/AboutYou/AddressHistory/reducer.js:1257:20)
      at Object.<anonymous> (app/reducers.js:248:36)
      at Object.<anonymous> (app/configureStore.js:217:36)
      at Object.<anonymous> (app/utils/tests/sagaInjectors.test.js:7:46)

**Comment by MakhBeth** [comment]
I have the same issue with 5.9.2 with all the import methods.

``` TypeError: Cannot read property 'indexOf' of null

      1 | import React from 'react'
    > 2 | import { init } from 'onfido-sdk-ui'
        | ^
      3 | import { Action } from './types'
      at Object.<anonymous> (node_modules/supports-webp/dist/supports-webp.common-js.js:6:62)
      at Object.require (node_modules/onfido-sdk-ui/lib/webpack:/external "supports-webp":1:18)
      at __webpack_require__ (node_modules/onfido-sdk-ui/lib/webpack:/webpack/bootstrap:25:67)
      at Module.<anonymous> (node_modules/onfido-sdk-ui/lib/index.js:17:419319)
      at __webpack_require__ (node_modules/onfido-sdk-ui/lib/webpack:/webpack/bootstrap:25:67)
      at module (node_modules/onfido-sdk-ui/lib/webpack:/external "preact":1:1)
      at Object.require (node_modules/onfido-sdk-ui/lib/webpack:/external "preact":1:18)```

**Comment by stefaniacardenas** [comment]
Hi @MakhBeth, are you using a framework that does server-side rendering first? If so, you should import the SDK asynchronously. Try importing it like in the example below and let me know if it works. 

```
let Onfido;
async componentDidMount() {
      Onfido = await import('onfido-sdk-ui')
}
Onfido.init()
```
