### ISSUE TITLE
Jest test case Fails

### ISSUE THREAD

**Issue by dhavalsoni2001** [onfido/onfido-sdk-ui#736]
I am using JEST for testing purpose. I am getting an error while running test cases because of onfido.

Here I am attaching the screenshot for the same.

![Screenshot 2019-07-18 at 12 16 57 PM](https://user-images.githubusercontent.com/11704436/61435384-f8067d80-a955-11e9-9429-c8256834ffb0.png)

**Comment by stefaniacardenas** [comment]
Hi, a similar issue was reported here #680 and solved by importing the library asynchronously I believe. Which version of the SDK are you using?

**Comment by dhavalsoni2001** [comment]
I was using version `5.2.2` and I also tried version `5.2.3` but facing the same issue.

**Comment by kopijunkie** [comment]
Hi @dhavalsoni2001 

Does the issue still happen even with the solution from the ticket @stefaniacardenas mentioned?

**Comment by dhavalsoni2001** [comment]
@kopijunkie Yes It's throwing the same error.

**Comment by kopijunkie** [comment]
Hi @dhavalsoni2001 

Are you able to share a sample project with us so that we can better understand and see where/how the Jest test case is failing?

**Comment by dhavalsoni2001** [comment]
Actually, I am also facing the issue for production build failed. : https://github.com/onfido/onfido-sdk-ui/issues/757

**Comment by kopijunkie** [comment]
@dhavalsoni2001 Do the app and tests work if you import the SDK this way:
```
import * as Onfido from "onfido-sdk-ui/dist/onfido.min.js"
import "onfido-sdk-ui/dist/style.css"
```
This is a workaround suggested in #615 that has worked for a few others

**Comment by stefaniacardenas** [comment]
The issues related with importing the library have been fixed in the latest release [5.3.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.3.0). Please refer to [this comment](https://github.com/onfido/onfido-sdk-ui/issues/615#issuecomment-529399981) in #615. I will close this issue for now, feel free to reopen if the problem is still there.

**Comment by dhavalsoni2001** [comment]
@stefaniacardenas 
 I am still facing the issue and I am on version 5.3.0

● Test suite failed to run

TypeError: Cannot read property 'indexOf' of null



  at Object.<anonymous> (node_modules/supports-webp/dist/supports-webp.common-js.js:6:62)
  at Object.<anonymous> (node_modules/onfido-sdk-ui/lib/index.js:12:47776)
  at n (node_modules/onfido-sdk-ui/lib/index.js:1:151)
  at Module.<anonymous> (node_modules/onfido-sdk-ui/lib/index.js:17:393988)
  at n (node_modules/onfido-sdk-ui/lib/index.js:1:151)
  at node_modules/onfido-sdk-ui/lib/index.js:1:1006
  at Object.<anonymous> (node_modules/onfido-sdk-ui/lib/index.js:1:1017)
  at Object.<anonymous> (app/containers/MyOffer/Overview/index.js:934:16)
  at Object.<anonymous> (app/containers/index.js:553:36)
  at Object.<anonymous> (app/containers/App/index.js:898:38)
  at Object.<anonymous> (app/app.js:22:35)
  at Object.<anonymous> (app/utils/commonFunctions.js:1966:8)
  at Object.<anonymous> (app/containers/MyApplication/AboutYou/AddressHistory/reducer.js:1257:20)
  at Object.<anonymous> (app/reducers.js:248:36)
  at Object.<anonymous> (app/configureStore.js:217:36)
  at Object.<anonymous> (app/utils/tests/sagaInjectors.test.js:7:46)

**Comment by stefaniacardenas** [comment]
Hi @dhavalsoni2001, have you got a demo you could share with us so I can inspect the code?
How are you importing the library? Are you lazy loading it? Thanks.
